checks:
    javascript: true
build:
    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
        tests: true

filter:
    excluded_paths: [backend/test/*]