version: '3'
services:
    phone:
            image: "davegeorge81/phone:1.0.2"
            environment:
                - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
                - REACT_NATIVE_PACKAGER_HOSTNAME=${IP}
            volumes:
                - ./phone-app/:/phone-app/
            ports:
                - '8081:8081'
                - '8082:8082'
                - '8083:8083'
            tty: true
            stdin_open: true
            command: npx expo start --clear
    express:
            build:
                context: ./
                dockerfile: ./backtest/Dockerfile
            volumes:
                - ./backtest/:/backtest/
            ports:
                - '3000:3000'
            command: node app.js
